#!/bin/sh

x() {
    n=$(basename "$1")
    [ -f "$n" ] && echo "$n already fetched" || wget "$1"
}
x http://ftp.gnu.org/gnu/binutils/binutils-2.25.1.tar.gz
x http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz
x http://ftp4.us.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/11.4/FreeBSD-11.4-RELEASE-amd64-dvd1.iso
x http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.3.tar.xz
x http://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
x http://ftp.gnu.org/gnu/gcc/gcc-4.8.5/gcc-4.8.5.tar.bz2
x http://ftp4.us.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/11.4/CHECKSUM.SHA256-FreeBSD-11.4-RELEASE-amd64

ISO_CHECKSUM=$(sha256sum --tag FreeBSD-11.4-RELEASE-amd64-dvd1.iso)
MATCHES=$(grep -c "$ISO_CHECKSUM" CHECKSUM.SHA256-FreeBSD-11.4-RELEASE-amd64)

if [ "$MATCHES" == "0" ]
then
    >&2 echo Checksum $ISO_CHECKSUM is incorrect.
    exit 1
fi

mkdir -p freebsd
(cd freebsd; 7z -aoa x ../FreeBSD-11.4-RELEASE-amd64-dvd1.iso usr/include)
(cd freebsd; 7z -aoa x ../FreeBSD-11.4-RELEASE-amd64-dvd1.iso usr/lib)
(cd freebsd; 7z -aoa x ../FreeBSD-11.4-RELEASE-amd64-dvd1.iso lib)

docker build -t freebsd-cross-build .
exit 0

